// This file was generated by img2gb, DO NOT EDIT
#include <types.h>
#ifndef _TILEMAP_H
#define _TILEMAP_H

extern const UINT8 BACKGROUNDTILEMAP[];
#define TILEMAP_WIDTH 20
#define TILEMAP_HEIGHT 18


#endif
