/*

 TESTFACE.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char TestFace[] =
{
  0x00,0x00,0x22,0x22,0x77,0x55,0x08,0x00,
  0x7F,0x7F,0x80,0x7F,0x62,0x3E,0x3C,0x1C,
  0x00,0x00,0x00,0x77,0x77,0x77,0x77,0x22,
  0x08,0x00,0x1C,0x1C,0x2C,0x30,0x20,0x00
};

/* End of TESTFACE.C */
