// This file was generated by img2gb, DO NOT EDIT

#ifndef _TILEMAPWALKER_0047_H
#define _TILEMAPWALKER_0047_H

extern const UINT8 TILEMAP[];
#define TILEMAP_WIDTH 3
#define TILEMAP_HEIGHT 3


#endif
