// This file was generated by img2gb, DO NOT EDIT

#ifndef _TILEMAPWALKER_0122_H
#define _TILEMAPWALKER_0122_H

extern const UINT8 TILEMAP[];
#define TILEMAP_WIDTH 3
#define TILEMAP_HEIGHT 3


#endif
